---
- name: Installing andrewrothstein.bash
  ansible.builtin.include_role:
    name: andrewrothstein.bash
- name: Installing andrewrothstein.git
  ansible.builtin.include_role:
    name: andrewrothstein.git
- name: Installing andrewrothstein.gcc_toolbox
  ansible.builtin.include_role:
    name: andrewrothstein.gcc_toolbox
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: Install os dep pkgs
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ ipxe_dep_os_pkgs | default([]) }}'

- name: Mkdir -p {{ ipxe_repos_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    path: '{{ ipxe_repos_dir }}'
    state: directory
    mode: '755'

- name: Cloning ipxe git repo at {{ ipxe_git_url }} to {{ ipxe_src_dir }}
  become: true
  become_user: root
  ansible.builtin.git:
    repo: '{{ ipxe_git_url }}'
    dest: '{{ ipxe_src_dir }}'
    version: '{{ ipxe_git_version }}'

- name: Linking {{ ipxe_src_link_dir }} to {{ ipxe_src_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ ipxe_src_dir }}'
    dest: '{{ ipxe_src_link_dir }}'
    state: link

- name: Make (bios) in {{ ipxe_src_link_dir }}
  become: true
  become_user: root
  ansible.builtin.command: make -j 4 -C src
  args:
    chdir: '{{ ipxe_src_link_dir }}'
  changed_when: false

- name: Make (everything) in {{ ipxe_src_link_dir }}
  become: true
  become_user: root
  ansible.builtin.command: make -j 4 -C src everything
  args:
    chdir: '{{ ipxe_src_link_dir }}'
  changed_when: false

- name: Add useful shell scriptlets for login shells
  become: true
  become_user: root
  with_items:
    - f: make-ipxe.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'
