---
- include_role:
    name: andrewrothstein.bash
- include_role:
    name: andrewrothstein.git
- include_role:
    name: andrewrothstein.gcc-toolbox
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: install dep pkgs
  become: true
  become_user: root
  package:
    name: '{{ ipxe_dep_os_pkgs|default([]) }}'

- name: ensure srcs directory exists...
  become: true
  become_user: root
  file:
    path: '{{ ipxe_repos_dir }}'
    state: directory
    mode: 0755

- name: clone ipxe git repo
  become: true
  become_user: root
  git:
    repo: '{{ ipxe_git_url }}'
    dest: '{{ ipxe_src_dir }}'

- name: convenience link...
  become: true
  become_user: root
  file:
    src: '{{ ipxe_src_dir }}'
    dest: '{{ ipxe_src_link_dir }}'
    state: link

- name: build...
  become: true
  become_user: root
  command: make
  args:
    chdir: '{{ ipxe_src_link_dir }}/src'

- name: install useful scripts...
  become: true
  become_user: root
  with_items:
    - f: make-ipxe-iso
      d: /usr/local/bin
    - f: make-ipxe-usb
      d: /usr/local/bin
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0755") }}'
